consumes:
    - application/json
    - multipart/form-data
produces:
    - application/json
schemes:
    - http
swagger: "2.0"
info:
    title: application-tracker
    version: 1.0.0
paths:
    /health:
        get:
            operationId: health
            responses:
                "200":
                    description: Health Check
                    schema:
                        $ref: '#/definitions/success'
                default:
                    schema:
                        $ref: '#/definitions/error'
                    description: Server Error
            security: []
            description: Check if the App is Running
            tags:
                - health
            summary: Health Check
    /v1/login:
        post:
            security: []
            description: Login
            tags:
                - authentication
            summary: Login
            operationId: login
            parameters:
                - name: data
                  in: body
                  schema:
                    $ref: '#/definitions/loginParamsBody'
            responses:
                default:
                    description: Server Error
                    schema:
                        $ref: '#/definitions/error'
                "201":
                    schema:
                        $ref: '#/definitions/successLogin'
                    headers:
                        token:
                            type: string
                    description: Success login
    /v1/profile:
        get:
            tags:
                - user
            summary: Find My User Data
            operationId: findMyUserData
            responses:
                "200":
                    description: Success fetch data
                    schema:
                        $ref: '#/definitions/myUserData'
                default:
                    schema:
                        $ref: '#/definitions/error'
                    description: Server Error
            security:
                - authorization: []
            description: Find my user data
    /v1/register:
        post:
            parameters:
                - name: data
                  in: body
                  schema:
                    $ref: '#/definitions/registerParamsBody'
            responses:
                "200":
                    schema:
                        $ref: '#/definitions/successRegister'
                    description: Success register
                default:
                    description: Server Error
                    schema:
                        $ref: '#/definitions/error'
            security: []
            description: Register user
            tags:
                - authentication
            summary: Register
            operationId: register
definitions:
    myUserData:
        type: object
        properties:
            username:
                x-omitempty: false
                type: string
    principal:
        type: object
        properties:
            expired_at:
                type: string
                format: date-time
            user_id:
                type: number
                format: uint64
            username:
                type: string
    modelIdentifier:
        type: object
        required:
            - id
        properties:
            id:
                type: integer
                format: uint64
    successLogin:
        allOf:
            - $ref: '#/definitions/success'
            - $ref: '#/definitions/successLoginAllOf1'
    modelTrackTime:
        type: object
        properties:
            created_at:
                type: string
                format: date-time
                x-go-custom-tag: gorm:"column:created_at"
                x-nullable: true
                x-omitempty: false
            deleted_at:
                x-omitempty: false
                type: string
                format: date-time
                x-go-custom-tag: gorm:"column:deleted_at"
                x-nullable: true
            updated_at:
                type: string
                format: date-time
                x-go-custom-tag: gorm:"column:updated_at"
                x-nullable: true
                x-omitempty: false
    successRegisterAllOf1:
        type: object
        properties:
            user_id:
                type: number
                format: uint64
        x-go-gen-location: models
    user:
        allOf:
            - $ref: '#/definitions/modelIdentifier'
            - $ref: '#/definitions/modelTrackTime'
            - $ref: '#/definitions/userData'
    userData:
        type: object
        properties:
            password:
                x-omitempty: false
                type: string
            username:
                x-omitempty: false
                type: string
    error:
        type: object
        properties:
            code:
                type: integer
            message:
                type: string
                example: error
    loginParamsBody:
        type: object
        required:
            - username
            - password
        properties:
            password:
                type: string
            username:
                type: string
        x-go-gen-location: operations
    successLoginAllOf1:
        x-go-gen-location: models
        type: object
        properties:
            expired_at:
                type: string
    successRegister:
        allOf:
            - $ref: '#/definitions/success'
            - $ref: '#/definitions/successRegisterAllOf1'
    registerParamsBody:
        required:
            - username
            - password
        properties:
            password:
                type: string
                minLength: !!float 8
            username:
                type: string
        x-go-gen-location: operations
        type: object
    success:
        type: object
        properties:
            message:
                type: string
securityDefinitions:
    authorization:
        name: Authorization
        in: header
        type: apiKey
