swagger: '2.0'
info:
  version: '1.0.0'
  title: application-tracker
schemes: [http]
consumes: [application/json, multipart/form-data]
produces: [application/json]
securityDefinitions:
  key:
    type: apiKey
    in: header
    name: Authorization

paths:
  # health
  /health:
    # $ref: "./path/v1/health/health.yml"
    get:
      tags: [health]
      summary: 'Health Check'
      description: 'Check if the App is Running'
      operationId: health
      security: []
      responses:
        200:
          description: 'Health Check'
          schema:
            $ref: '#/definitions/Success'
        default:
          schema:
            $ref: '#/definitions/Error'
          description: Server Error

definitions:
  principal:
    type: object
    properties:
      email:
        type: string
      user_id:
        type: number
        format: uint64
      expired_at:
        type: string

  Error:
    type: object
    properties:
      code:
        type: integer
      message:
        type: string
        example: 'error'

  Success:
    type: object
    properties:
      message:
        type: string
