# Generated by Django 4.2.2 on 2023-06-12 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('platform', models.CharField(max_length=255)),
                ('source_link', models.CharField(max_length=255)),
                ('last_updated', models.TimeField()),
                ('last_status', models.CharField(choices=[('A', 'Applied'), ('ST', 'Skill Test'), ('IH', 'Interview HR'), ('IU', 'Interview User'), ('RR', 'Rejected Resume'), ('RST', 'Rejected Skill Test'), ('RH', 'Rejected HR'), ('RU', 'Rejected User'), ('TK', 'Tidak Kukerjakan'), ('D', 'Dikeep'), ('O', 'Offering')], max_length=50)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Applied'), ('ST', 'Skill Test'), ('IH', 'Interview HR'), ('IU', 'Interview User'), ('RR', 'Rejected Resume'), ('RST', 'Rejected Skill Test'), ('RH', 'Rejected HR'), ('RU', 'Rejected User'), ('TK', 'Tidak Kukerjakan'), ('D', 'Dikeep'), ('O', 'Offering')], max_length=50)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application_tracker.application')),
            ],
        ),
    ]
