# Generated by Django 4.2.2 on 2023-06-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_tracker', '0002_alter_application_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
