# Generated by Django 4.2.3 on 2025-01-20 01:26

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('application_tracker', '0002_alter_application_user_alter_applicationstatus_user_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='applicationstatus',
            name='unique_application_status',
        ),
        migrations.RemoveConstraint(
            model_name='platform',
            name='unique_platform',
        ),
        migrations.AddConstraint(
            model_name='applicationstatus',
            constraint=models.UniqueConstraint(models.F('user_id'), django.db.models.functions.text.Lower('name'), name='unique_application_status'),
        ),
        migrations.AddConstraint(
            model_name='platform',
            constraint=models.UniqueConstraint(models.F('user_id'), django.db.models.functions.text.Lower('name'), name='unique_platform'),
        ),
    ]
